In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import joblib

# Load the cleaned dataset
file_path = r"C:\Users\annad\Downloads\rental_app_dataset_cleaned.csv"  # Change if needed
df = pd.read_csv(file_path)

# Define features and target variable
X = df.drop(columns=["Rating"])
y = df["Rating"]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a RandomForest model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

# Save the trained model
joblib.dump(model, "rental_rating_model.pkl")

# Display a few predictions
print("Sample Predictions:")
print(pd.DataFrame({"Actual": y_test.values, "Predicted": y_pred}).head())

Mean Squared Error: 0.09989408562499999
Sample Predictions:
   Actual  Predicted
0   0.600    0.56400
1   0.950    0.26750
2   0.450    0.52025
3   0.925    0.43475
4   0.900    0.27750

In [2]:
df

     Equipment  Rent per Day  Successful Rentals  Rating
0            6      0.521854            0.128889   0.150
1            3      0.866245            0.288889   0.300
2            7      0.862559            0.913333   0.875
3            4      0.434966            0.446667   1.000
4            6      0.358610            0.537778   0.375
..         ...           ...                 ...     ...
995          9      0.347551            0.968889   0.525
996          9      0.288046            0.835556   0.050
997          7      0.723539            0.042222   0.975
998          1      0.163244            0.164444   0.225
999          8      0.458662            0.886667   0.300

[1000 rows x 4 columns]